artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/cicdataset/cicids2017
  dataset_ID: cicdataset/cicids2017
  local_data_file: artifacts/data_ingestion/cicdataset
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/cicdataset
  merged_csv_file: artifacts/data_validation/network_traffic_anomaly.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/network_traffic_anomaly.csv
  preprocessed_data: artifacts/data_transformation/preprocessed_anomaly.csv